### model
model_name_or_path: /work/model/Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full 

### dataset
dataset: ImageGen-CoT-Reward-5K
media_dir: /work/LLaMA-Factory/data/CodeGoat24/ImageGen-CoT-Reward-5K
template: qwen2_vl
cutoff_len: 2048 # 这是显存消耗大户，如果全参微调OOM，可以考虑降到1536或1024
max_samples: 5540 
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl_3b/full/sft/ImageGen-CoT-Reward-5K 
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 1 
gradient_accumulation_steps: 8 
learning_rate: 2.0e-6 
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
optim: adamw_8bit
bf16: true 
ddp_timeout: 180000000
weight_decay: 0.01
max_grad_norm: 1.0

### eval
val_size: 0.05
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 200